main: spigot.zanos.plugin.FileEncoder
name: FileEncoder
version: '1.0.0'
description: Plugin to encode and decode your files into/from minecraft blocks.
api-version: '1.20'
load: POSTWORLD
author: Zanos - Philipp von Neffe

commands:
  encode:
    description: "Encode your file into minecraft blocks. Default: base16"
    usage: /encode [base2 | base16]
  decode:
    description: "Decode your file back into a regular file"
    usage: /decode

